package com.pacoillan.pojo;
// Generated 15-nov-2017 22:04:53 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cpostal generated by hbm2java
 */
@Entity
@Table(name="cpostal"
    ,catalog="pacoillan2"
)
public class Cpostal  implements java.io.Serializable {


     private int codigo;
     private String poblacion;

    public Cpostal() {
    }

    public Cpostal(int codigo, String poblacion) {
       this.codigo = codigo;
       this.poblacion = poblacion;
    }
   
     @Id 
    
    @Column(name="codigo", unique=true, nullable=false)
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    
    @Column(name="poblacion", nullable=false, length=25)
    public String getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(String poblacion) {
        this.poblacion = poblacion;
    }




}


