package com.pacoillan.pojo;
// Generated 15-ago-2016 10:55:19 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Entidad generated by hbm2java
 */
@Entity
@Table(name="entidad"
    ,catalog="pacoillan2"
)
public class Entidad  implements java.io.Serializable, Comparable {


     private Integer idEntidad;
     private String nombreEntidad;
     private String direccionEntidad;
     private String cPostalEntidad;
     private String poblacionEntidad;
     private String dniEntidad;
     private String telefonoEntidad;
     private String movilEntidad;
     private String emailEntidad;
     private String infoEntidad;

    public Entidad() {
    }

    public Entidad(String nombreEntidad, String direccionEntidad, String cPostalEntidad,
            String poblacionEntidad, String dniEntidad, String telefonoEntidad,
            String movilEntidad, String emailEntidad, String infoEntidad) {
       this.nombreEntidad = nombreEntidad;
       this.direccionEntidad = direccionEntidad;
       this.cPostalEntidad = cPostalEntidad;
       this.poblacionEntidad = poblacionEntidad;
       this.dniEntidad = dniEntidad;
       this.telefonoEntidad = telefonoEntidad;
       this.movilEntidad = movilEntidad;
       this.emailEntidad = emailEntidad;
       this.infoEntidad = infoEntidad;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)    
    @Column(name="idEntidad", unique=true, nullable=false)
    public Integer getIdEntidad() {
        return this.idEntidad;
    }
    
    public void setIdEntidad(Integer idEntidad) {
        this.idEntidad = idEntidad;
    }
    
    @Column(name="nombreEntidad", length=35)
    public String getNombreEntidad() {
        return this.nombreEntidad;
    }
    
    public void setNombreEntidad(String nombreEntidad) {
        this.nombreEntidad = nombreEntidad;
    }
    
    @Column(name="direccionEntidad", length=25)
    public String getDireccionEntidad() {
        return this.direccionEntidad;
    }
    
    public void setDireccionEntidad(String direccionEntidad) {
        this.direccionEntidad = direccionEntidad;
    }
    
    @Column(name="cPostalEntidad", length=5)
    public String getCPostalEntidad() {
        return this.cPostalEntidad;
    }
    
    public void setCPostalEntidad(String cPostalEntidad) {
        this.cPostalEntidad = cPostalEntidad;
    }
    
    @Column(name="poblacionEntidad", length=25)
    public String getPoblacionEntidad() {
        return this.poblacionEntidad;
    }
    
    public void setPoblacionEntidad(String poblacionEntidad) {
        this.poblacionEntidad = poblacionEntidad;
    }
    
    @Column(name="dniEntidad", length=9)
    public String getDniEntidad() {
        return this.dniEntidad;
    }
    
    public void setDniEntidad(String dniEntidad) {
        this.dniEntidad = dniEntidad;
    }
    
    @Column(name="telefonoEntidad", length=12)
    public String getTelefonoEntidad() {
        return this.telefonoEntidad;
    }
    
    public void setTelefonoEntidad(String telefonoEntidad) {
        this.telefonoEntidad = telefonoEntidad;
    }
    
    @Column(name="movilEntidad", length=12)
    public String getMovilEntidad() {
        return this.movilEntidad;
    }
    
    public void setMovilEntidad(String movilEntidad) {
        this.movilEntidad= movilEntidad;
    }
    
    @Column(name="emailEntidad", length=30)
    public String getEmailEntidad() {
        return this.emailEntidad;
    }
    
    public void setEmailEntidad(String emailEntidad) {
        this.emailEntidad = emailEntidad;
    }
    
    @Column(name="infoEntidad", length=2000)
    public String getInfoEntidad() {
        return this.infoEntidad;
    }
    
    public void setInfoEntidad(String infoEntidad) {
        this.infoEntidad = infoEntidad;
    }

    @Override
    public int compareTo(Object t) {
        Entidad otraEntidad = (Entidad) t;
        return nombreEntidad.compareTo(otraEntidad.getNombreEntidad()); // Ordena alfabeticamente por nombre
       
    }

}


