package com.pacoillan.pojo;
// Generated 10-may-2016 22:57:56 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Fabricante generated by hbm2java
 */
@Entity
@Table(name="fabricante"
    ,catalog="pacoillan2"
)
public class Fabricante  implements java.io.Serializable {


     private Integer idFabricante;
     private String codigoFabricante;
     private String nombreFabricante;
     private String logoFabricante;

    public Fabricante() {
    }

    public Fabricante(String codigoFabricante, String nombreFabricante, String logoFabricante) {
       this.codigoFabricante = codigoFabricante;
       this.nombreFabricante = nombreFabricante;
       this.logoFabricante = logoFabricante;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_fabricante", unique=true, nullable=false)
    public Integer getIdFabricante() {
        return this.idFabricante;
    }
    
    public void setIdFabricante(Integer idFabricante) {
        this.idFabricante = idFabricante;
    }
    
    @Column(name="codigoFabricante", nullable=false, length=5)
    public String getCodigoFabricante() {
        return this.codigoFabricante;
    }
    
    public void setCodigoFabricante(String codigoFabricante) {
        this.codigoFabricante = codigoFabricante;
    }
    
    @Column(name="nombreFabricante", nullable=false, length=30)
    public String getNombreFabricante() {
        return this.nombreFabricante;
    }
    
    public void setNombreFabricante(String nombreFabricante) {
        this.nombreFabricante = nombreFabricante;
    }
    
    @Column(name="logoFabricante", nullable=false, length=30)
    public String getLogoFabricante() {
        return this.logoFabricante;
    }
    
    public void setLogoFabricante(String logoFabricante) {
        this.logoFabricante = logoFabricante;
    }




}


