package com.pacoillan.pojo;
// Generated 10-may-2016 22:57:56 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Fabricante generated by hbm2java
 */
@Entity
@Table(name="fabricante"
    ,catalog="pacoillan2"
)
public class Fabricante  implements java.io.Serializable {


     private Integer idFabricante;
     private String codigo;
     private String nombre;
     private String logo;

    public Fabricante() {
    }

    public Fabricante(String codigo, String nombre, String logo) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.logo = logo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_fabricante", unique=true, nullable=false)
    public Integer getIdFabricante() {
        return this.idFabricante;
    }
    
    public void setIdFabricante(Integer idFabricante) {
        this.idFabricante = idFabricante;
    }
    
    @Column(name="codigo", nullable=false, length=5)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    
    @Column(name="nombre", nullable=false, length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="logo", nullable=false, length=30)
    public String getLogo() {
        return this.logo;
    }
    
    public void setLogo(String logo) {
        this.logo = logo;
    }




}


