package com.pacoillan.pojo;
// Generated 10-may-2016 23:00:25 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Modelo generated by hbm2java
 */
@Entity
@Table(name="modelo"
    ,catalog="pacoillan2"
)
public class Modelo  implements java.io.Serializable {


     private Integer idModelo;
     private String codigo;
     private Fabricante fabricante;
     private String descripcion;
     private int mesInicio;
     private int yearInicio;
     private int mesFin;
     private int yearFin;
     private String imagen;

    public Modelo() {
    }

    public Modelo(String codigo, Fabricante fabricante, String descripcion, int mesInicio, int yearInicio, int mesFin, int yearFin, String imagen) {
       this.codigo = codigo;
       this.fabricante = fabricante;
       this.descripcion = descripcion;
       this.mesInicio = mesInicio;
       this.yearInicio = yearInicio;
       this.mesFin = mesFin;
       this.yearFin = yearFin;
       this.imagen = imagen;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idModelo", unique=true, nullable=false)
    public Integer getIdModelo() {
        return this.idModelo;
    }
    
    public void setIdModelo(Integer idModelo) {
        this.idModelo = idModelo;
    }
    
    @Column(name="codigo", nullable=false, length=10)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    
    @OneToOne
    @JoinColumn(name = "idMarca", nullable = false)
    public Fabricante getFabricante() {
        return this.fabricante;
    }
    
    public void setFabricante(Fabricante fabricante) {
        this.fabricante = fabricante;
    }
    
    @Column(name="descripcion", nullable=false, length=30)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="mesInicio", nullable=false)
    public int getMesInicio() {
        return this.mesInicio;
    }
    
    public void setMesInicio(int mesInicio) {
        this.mesInicio = mesInicio;
    }
    
    @Column(name="yearInicio", nullable=false)
    public int getYearInicio() {
        return this.yearInicio;
    }
    
    public void setYearInicio(int yearInicio) {
        this.yearInicio = yearInicio;
    }
    
    @Column(name="mesFin", nullable=false)
    public int getMesFin() {
        return this.mesFin;
    }
    
    public void setMesFin(int mesFin) {
        this.mesFin = mesFin;
    }
    
    @Column(name="yearFin", nullable=false)
    public int getYearFin() {
        return this.yearFin;
    }
    
    public void setYearFin(int yearFin) {
        this.yearFin = yearFin;
    }
    
    @Column(name="imagen", nullable=false, length=20)
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }




}


