package com.pacoillan.pojo;
// Generated 10-may-2016 23:00:25 by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Modelo generated by hbm2java
 */
@Entity
@Table(name = "modelo", catalog = "pacoillan2")
public class Modelo implements java.io.Serializable, Comparable {

    private Integer idModelo;
    private String codigoModelo;
    private Fabricante fabricante;
    private String descripcionModelo;
    private String inicioModelo;
    private String finModelo;
    private String imagenModelo;

    public Modelo() {
    }

    public Modelo(String codigoModelo, Fabricante fabricante, String descripcionModelo, String inicioModelo, String finModelo, String imagenModelo) {
        this.codigoModelo = codigoModelo;
        this.fabricante = fabricante;
        this.descripcionModelo = descripcionModelo;
        this.inicioModelo = inicioModelo;
        this.finModelo = finModelo;
        this.imagenModelo = imagenModelo;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idModelo", unique = true, nullable = false)
    public Integer getIdModelo() {
        return this.idModelo;
    }

    public void setIdModelo(Integer idModelo) {
        this.idModelo = idModelo;
    }

    @Column(name = "codigoModelo", nullable = false, length = 10)
    public String getCodigoModelo() {
        return this.codigoModelo;
    }

    public void setCodigoModelo(String codigoModelo) {
        this.codigoModelo = codigoModelo;
    }

    @OneToOne
    @JoinColumn(name = "idMarca", nullable = false)
    public Fabricante getFabricante() {
        return this.fabricante;
    }

    public void setFabricante(Fabricante fabricante) {
        this.fabricante = fabricante;
    }

    @Column(name = "descripcionModelo", nullable = false, length = 30)
    public String getDescripcionModelo() {
        return this.descripcionModelo;
    }

    public void setDescripcionModelo(String descripcionModelo) {
        this.descripcionModelo = descripcionModelo;
    }

    @Column(name = "inicioModelo", nullable = false)
    public String getInicioModelo() {
        return this.inicioModelo;
    }

    public void setInicioModelo(String inicioModelo) {
        this.inicioModelo = inicioModelo;
    }

    @Column(name = "finModelo", nullable = false)
    public String getFinModelo() {
        return this.finModelo;
    }

    public void setFinModelo(String finModelo) {
        this.finModelo = finModelo;
    }

    @Column(name = "imagenModelo", nullable = false, length = 20)
    public String getImagenModelo() {
        return this.imagenModelo;
    }

    public void setImagenModelo(String imagenModelo) {
        this.imagenModelo = imagenModelo;
    }

    @Override
    public int compareTo(Object t) {
        Modelo otroModelo = (Modelo) t;
        return codigoModelo.compareTo(otroModelo.getCodigoModelo());
    }
}
