package com.pacoillan.pojo;
// Generated 10-may-2016 23:00:25 by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Modelo generated by hbm2java
 */
@Entity
@Table(name = "modelo", catalog = "pacoillan2")
public class Modelo implements java.io.Serializable, Comparable {

    private Integer idModelo;
    private String codigo;
    private Fabricante fabricante;
    private String descripcion;
    private String fechaInicio;
    private String fechaFin;
    private String imagen;

    public Modelo() {
    }

    public Modelo(String codigo, Fabricante fabricante, String descripcion, String fechaInicio, String fechaFin, String imagen) {
        this.codigo = codigo;
        this.fabricante = fabricante;
        this.descripcion = descripcion;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
        this.imagen = imagen;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idModelo", unique = true, nullable = false)
    public Integer getIdModelo() {
        return this.idModelo;
    }

    public void setIdModelo(Integer idModelo) {
        this.idModelo = idModelo;
    }

    @Column(name = "codigo", nullable = false, length = 10)
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    @OneToOne
    @JoinColumn(name = "idMarca", nullable = false)
    public Fabricante getFabricante() {
        return this.fabricante;
    }

    public void setFabricante(Fabricante fabricante) {
        this.fabricante = fabricante;
    }

    @Column(name = "descripcion", nullable = false, length = 30)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "fechaInicio", nullable = false)
    public String getFechaInicio() {
        return this.fechaInicio;
    }

    public void setFechaInicio(String fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Column(name = "fechaFin", nullable = false)
    public String getFechaFin() {
        return this.fechaFin;
    }

    public void setFechaFin(String fechaFin) {
        this.fechaFin = fechaFin;
    }

    @Column(name = "imagen", nullable = false, length = 20)
    public String getImagen() {
        return this.imagen;
    }

    public void setImagen(String imagen) {
        this.imagen = imagen;
    }

    @Override
    public int compareTo(Object t) {
        Modelo otroModelo = (Modelo) t;
        return codigo.compareTo(otroModelo.getCodigo());
    }
}
