package com.pacoillan.pojo;
// Generated 28-mar-2015 0:33:52 by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Motor generated by hbm2java
 */
@Entity
@Table(name = "motor", catalog = "pacoillan2")
public class Motor implements java.io.Serializable, Comparable {

    private Integer idMotor;
    private String codigo;
    private String descripcion;
    private String combustible;
    private String cilindrada;
    private Float kw;
    private Fabricante fabricante;

    public Motor() {
    }
    
    public Motor(String codigo){
        this.codigo = codigo;
    }

    public Motor(String codigo, String descripcion) {  // Constructor necesario para line en blanco listados
        this.codigo = codigo;
        this.descripcion = descripcion;
    }

    public Motor(String codigo, String descripcion, String combustible, String cilindrada, Float kw, Fabricante fabricante) {
        this.codigo = codigo;
        this.descripcion = descripcion;
        this.combustible = combustible;
        this.cilindrada = cilindrada;
        this.kw = kw;
        this.fabricante = fabricante;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idMotor", unique = true, nullable = false)
    public Integer getIdMotor() {
        return this.idMotor;
    }

    public void setIdMotor(Integer idMotor) {
        this.idMotor = idMotor;
    }

    @Column(name = "codigo", nullable = false, length = 10)
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    @Column(name = "descripcion", nullable = false, length = 40)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "combustible", nullable = false, length = 2)
    public String getCombustible() {
        return this.combustible;
    }

    public void setCombustible(String combustible) {
        this.combustible = combustible;
    }

    @Column(name = "cilindrada", length = 5)
    public String getCilindrada() {
        return this.cilindrada;
    }

    public void setCilindrada(String cilindrada) {
        this.cilindrada = cilindrada;
    }

    @Column(name = "kw", precision = 12, scale = 0)
    public Float getKw() {
        return this.kw;
    }

    public void setKw(Float kw) {
        this.kw = kw;
    }

    @OneToOne
    @JoinColumn(name = "idMarca", nullable = false)
    public Fabricante getFabricante() {
        return this.fabricante;
    }

    public void setFabricante(Fabricante fabricante) {
        this.fabricante = fabricante;
    }

    @Override
    public int compareTo(Object t) {
        Motor otraMotor = (Motor) t;
        return codigo.compareTo(otraMotor.getCodigo());
    }
}
