package com.pacoillan.pojo;
// Generated 14-sep-2016 22:54:45 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vehiculo generated by hbm2java
 */
@Entity
@Table(name = "vehiculo", catalog = "pacoillan2")
public class Vehiculo implements java.io.Serializable {

    private Integer idVehiculo;
    private String matricula;
    private String chasis;
    private Modelo modelo;
    private Motor motor;
    private Date fechaMatricula;
    private Entidad entidad;
    private String informacion;

    public Vehiculo() {
    }

    public Vehiculo(String matricula, String chasis, Date fechaMatricula, String informacion) {
        this.matricula = matricula;
        this.chasis = chasis;
        this.fechaMatricula = fechaMatricula;
        this.informacion = informacion;
    }

    public Vehiculo(String matricula, String chasis, Modelo modelo, Motor motor, Entidad entidad, String informacion) {
        this.matricula = matricula;
        this.chasis = chasis;
        this.modelo = modelo;
        this.motor = motor;
        this.entidad = entidad;
        this.informacion = informacion;
    }

    public Vehiculo(String matricula, String chasis, Modelo modelo, Motor motor, Date fechaMatricula, Entidad entidad, String informacion) {
        this.matricula = matricula;
        this.chasis = chasis;
        this.modelo = modelo;
        this.motor = motor;
        this.fechaMatricula = fechaMatricula;
        this.entidad = entidad;
        this.informacion = informacion;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idVehiculo", unique = true, nullable = false)
    public Integer getIdVehiculo() {
        return this.idVehiculo;
    }

    public void setIdVehiculo (Integer idVehiculo) {
        this.idVehiculo = idVehiculo;
    }

    @Column(name = "matricula", nullable = false, length = 12)
    public String getMatricula() {
        return this.matricula;
    }

    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }

    @Column(name = "chasis", nullable = false, length = 20)
    public String getChasis() {
        return this.chasis;
    }

    public void setChasis(String chasis) {
        this.chasis = chasis;
    }

    @OneToOne
    @JoinColumn(name = "idModelo", nullable = false)
    public Modelo getModelo() {
        return this.modelo;
    }

    public void setModelo(Modelo modelo) {
        this.modelo = modelo;
    }

    @OneToOne
    @JoinColumn(name = "idMotor", nullable = false)
    public Motor getMotor() {
        return this.motor;
    }

    public void setMotor(Motor motor) {
        this.motor = motor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fechaMatricula", length = 10)
    public Date getFechaMatricula() {
        return this.fechaMatricula;
    }

    public void setFechaMatricula(Date fechaMatricula) {
        this.fechaMatricula = fechaMatricula;
    }

    @OneToOne
    @JoinColumn(name = "idEntidad", nullable = false)
    public Entidad getEntidad() {
        return this.entidad;
    }

    public void setEntidad(Entidad entidad) {
        this.entidad = entidad;
    }

    @Column(name = "informacion", length = 2000)
    public String getInformacion() {
        return informacion;
    }

    public void setInformacion(String informacion) {
        this.informacion = informacion;
    }
}
